
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/sht/sSelect
	@mkdir  ../../sea-modules/sht/sSelect
	@mkdir  ../../sea-modules/sht/sSelect/1.0.0
	@cp     dist/*.* ../../sea-modules/sht/sSelect/1.0.0
	@echo
	@echo   " deploy to ../../seajs-modules/sht/sSelect/1.0.0" 
	@echo
