
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/sht/picPlayer
	@mkdir  ../../sea-modules/sht/picPlayer
	@mkdir  ../../sea-modules/sht/picPlayer/1.0.0
	@cp     dist/*.* ../../sea-modules/sht/picPlayer/1.0.0
	@echo
	@echo   " deploy to ../../seajs-modules/sht/picPlayer/1.0.0"
	@echo
