
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/sht/timer
	@mkdir  ../../sea-modules/sht/timer
	@mkdir  ../../sea-modules/sht/timer/1.0.0
	@cp     dist/*.* ../../sea-modules/sht/timer/1.0.0
	@echo
	@echo   " deploy to ../../seajs-modules/sht/timer/1.0.0" 
	@echo
