
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/sht/pnumview
	@mkdir  ../../sea-modules/sht/pnumview
	@mkdir  ../../sea-modules/sht/pnumview/1.0.0
	@cp     dist/*.* ../../sea-modules/sht/pnumview/1.0.0
	@echo
	@echo   " deploy to ../../seajs-modules/sht/pnumview/1.0.0" 
	@echo
